package operatingsystem

// OperatingSystems maps short codes to full OS names.
// Mirrors PHP OperatingSystem::$operatingSystems
var OperatingSystems = map[string]string{
	"AIX": "AIX",
	"AND": "Android",
	"ADR": "Android TV",
	"ALP": "Alpine Linux",
	"AMZ": "Amazon Linux",
	"AMG": "AmigaOS",
	"ARM": "Armadillo OS",
	"ARO": "AROS",
	"ATV": "tvOS",
	"ARL": "Arch Linux",
	"AOS": "AOSC OS",
	"ASP": "ASPLinux",
	"AZU": "Azure Linux",
	"BTR": "BackTrack",
	"SBA": "Bada",
	"BYI": "Baidu Yi",
	"BEO": "BeOS",
	"BLB": "BlackBerry OS",
	"QNX": "BlackBerry Tablet OS",
	"PAN": "blackPanther OS",
	"BOS": "Bliss OS",
	"BMP": "Brew",
	"BSN": "BrightSignOS",
	"CAI": "Caixa Mágica",
	"CES": "CentOS",
	"CST": "CentOS Stream",
	"CLO": "Clear Linux OS",
	"CLR": "ClearOS Mobile",
	"COS": "Chrome OS",
	"CRS": "Chromium OS",
	"CHN": "China OS",
	"COL": "Coolita OS",
	"CYN": "CyanogenMod",
	"DEB": "Debian",
	"DEE": "Deepin",
	"DFB": "DragonFly",
	"DVK": "DVKBuntu",
	"ELE": "ElectroBSD",
	"EUL": "EulerOS",
	"FED": "Fedora",
	"FEN": "Fenix",
	"FOS": "Firefox OS",
	"FIR": "Fire OS",
	"FOR": "Foresight Linux",
	"FRE": "Freebox",
	"BSD": "FreeBSD",
	"FRI": "FRITZ!OS",
	"FYD": "FydeOS",
	"FUC": "Fuchsia",
	"GNT": "Gentoo",
	"GNX": "GENIX",
	"GEO": "GEOS",
	"GNS": "gNewSense",
	"GRI": "GridOS",
	"GTV": "Google TV",
	"HPX": "HP-UX",
	"HAI": "Haiku OS",
	"IPA": "iPadOS",
	"HAR": "HarmonyOS",
	"HAS": "HasCodingOS",
	"HEL": "HELIX OS",
	"IRI": "IRIX",
	"INF": "Inferno",
	"JME": "Java ME",
	"JOL": "Joli OS",
	"KOS": "KaiOS",
	"KAL": "Kali",
	"KAN": "Kanotix",
	"KIN": "KIN OS",
	"KOL": "KolibriOS",
	"KNO": "Knoppix",
	"KTV": "KreaTV",
	"KBT": "Kubuntu",
	"LIN": "GNU/Linux",
	"LEA": "LeafOS",
	"LND": "LindowsOS",
	"LNS": "Linspire",
	"LEN": "Lineage OS",
	"LIR": "Liri OS",
	"LOO": "Loongnix",
	"LBT": "Lubuntu",
	"LOS": "Lumin OS",
	"LUN": "LuneOS",
	"VLN": "VectorLinux",
	"MAC": "Mac",
	"MAE": "Maemo",
	"MAG": "Mageia",
	"MDR": "Mandriva",
	"SMG": "MeeGo",
	"MET": "Meta Horizon",
	"MCD": "MocorDroid",
	"MON": "moonOS",
	"EZX": "Motorola EZX",
	"MIN": "Mint",
	"MLD": "MildWild",
	"MOR": "MorphOS",
	"NBS": "NetBSD",
	"MTK": "MTK / Nucleus",
	"MRE": "MRE",
	"NXT": "NeXTSTEP",
	"NWS": "NEWS-OS",
	"WII": "Nintendo",
	"NDS": "Nintendo Mobile",
	"NOV": "Nova",
	"OS2": "OS/2",
	"T64": "OSF1",
	"OBS": "OpenBSD",
	"OHS": "OpenHarmony",
	"OVS": "OpenVMS",
	"OVZ": "OpenVZ",
	"OWR": "OpenWrt",
	"OTV": "Opera TV",
	"ORA": "Oracle Linux",
	"ORD": "Ordissimo",
	"PAR": "Pardus",
	"PCL": "PCLinuxOS",
	"PIC": "PICO OS",
	"PLA": "Plasma Mobile",
	"PSP": "PlayStation Portable",
	"PS3": "PlayStation",
	"PVE": "Proxmox VE",
	"PUF": "Puffin OS",
	"PUR": "PureOS",
	"QTP": "Qtopia",
	"PIO": "Raspberry Pi OS",
	"RAS": "Raspbian",
	"RHT": "Red Hat",
	"RST": "Red Star",
	"RED": "RedOS",
	"REV": "Revenge OS",
	"RIS": "risingOS",
	"ROS": "RISC OS",
	"ROC": "Rocky Linux",
	"ROK": "Roku OS",
	"RSO": "Rosa",
	"ROU": "RouterOS",
	"REM": "Remix OS",
	"RRS": "Resurrection Remix OS",
	"REX": "REX",
	"RZD": "RazoDroiD",
	"RXT": "RTOS & Next",
	"SAB": "Sabayon",
	"SSE": "SUSE",
	"SAF": "Sailfish OS",
	"SCI": "Scientific Linux",
	"SEE": "SeewoOS",
	"SER": "SerenityOS",
	"SIR": "Sirin OS",
	"SLW": "Slackware",
	"SMA": "Smartisan OS",
	"SOS": "Solaris",
	"SBL": "Star-Blade OS",
	"SYL": "Syllable",
	"SYM": "Symbian",
	"SYS": "Symbian OS",
	"S40": "Symbian OS Series 40",
	"S60": "Symbian OS Series 60",
	"SY3": "Symbian^3",
	"TEN": "TencentOS",
	"TDX": "ThreadX",
	"TIT": "Titan OS",
	"TIZ": "Tizen",
	"TIV": "TiVo OS",
	"TOS": "TmaxOS",
	"TUR": "Turbolinux",
	"UBT": "Ubuntu",
	"ULT": "ULTRIX",
	"UOS": "UOS",
	"VID": "VIDAA",
	"VIZ": "ViziOS",
	"WAS": "watchOS",
	"WER": "Wear OS",
	"WTV": "WebTV",
	"WHS": "Whale OS",
	"WIN": "Windows",
	"WCE": "Windows CE",
	"WIO": "Windows IoT",
	"WMO": "Windows Mobile",
	"WPH": "Windows Phone",
	"WRT": "Windows RT",
	"WPO": "WoPhone",
	"XBX": "Xbox",
	"XBT": "Xubuntu",
	"YNS": "YunOS",
	"ZEN": "Zenwalk",
	"ZOR": "ZorinOS",
	"IOS": "iOS",
	"POS": "palmOS",
	"WEB": "Webian",
	"WOS": "webOS",
}

// OSFamilies maps OS family names to short codes of member OSes.
// Mirrors PHP OperatingSystem::$osFamilies
var OSFamilies = map[string][]string{
	"Android": {
		"AND", "CYN", "FIR", "REM", "RZD", "MLD", "MCD", "YNS", "GRI", "HAR",
		"ADR", "CLR", "BOS", "REV", "LEN", "SIR", "RRS", "WER", "PIC", "ARM",
		"HEL", "BYI", "RIS", "PUF", "LEA", "MET", "OHS", "SMA",
	},
	"AmigaOS":        {"AMG", "MOR", "ARO"},
	"BlackBerry":     {"BLB", "QNX"},
	"Brew":           {"BMP"},
	"BeOS":           {"BEO", "HAI"},
	"Chrome OS":      {"COS", "CRS", "FYD", "SEE"},
	"Firefox OS":     {"FOS", "KOS"},
	"Gaming Console": {"WII", "PS3"},
	"Google TV":      {"GTV"},
	"IBM":            {"OS2"},
	"iOS":            {"IOS", "ATV", "WAS", "IPA"},
	"RISC OS":        {"ROS"},
	"GNU/Linux": {
		"LIN", "ARL", "DEB", "KNO", "MIN", "UBT", "KBT", "XBT", "LBT", "FED",
		"RHT", "VLN", "MDR", "GNT", "SAB", "SLW", "SSE", "CES", "BTR", "SAF",
		"ORD", "TOS", "RSO", "DEE", "FRE", "MAG", "FEN", "CAI", "PCL", "HAS",
		"LOS", "DVK", "ROK", "OWR", "OTV", "KTV", "PUR", "PLA", "FUC", "PAR",
		"FOR", "MON", "KAN", "ZEN", "LND", "LNS", "CHN", "AMZ", "TEN", "CST",
		"NOV", "ROU", "ZOR", "RED", "KAL", "ORA", "VID", "TIV", "BSN", "RAS",
		"UOS", "PIO", "FRI", "LIR", "WEB", "SER", "ASP", "AOS", "LOO", "EUL",
		"SCI", "ALP", "CLO", "ROC", "OVZ", "PVE", "RST", "EZX", "GNS", "JOL",
		"TUR", "QTP", "WPO", "PAN", "VIZ", "AZU", "COL",
	},
	"Mac":                   {"MAC"},
	"Mobile Gaming Console": {"PSP", "NDS", "XBX"},
	"OpenVMS":               {"OVS"},
	"Real-time OS":          {"MTK", "TDX", "MRE", "JME", "REX", "RXT", "KOL"},
	"Other Mobile":          {"WOS", "POS", "SBA", "TIZ", "SMG", "MAE", "LUN", "GEO"},
	"Symbian":               {"SYM", "SYS", "SY3", "S60", "S40"},
	"Unix": {
		"SOS", "AIX", "HPX", "BSD", "NBS", "OBS", "DFB", "SYL", "IRI", "T64",
		"INF", "ELE", "GNX", "ULT", "NWS", "NXT", "SBL",
	},
	"WebTV":          {"WTV"},
	"Windows":        {"WIN"},
	"Windows Mobile": {"WPH", "WMO", "WCE", "WRT", "WIO", "KIN"},
	"Other Smart TV": {"WHS", "TIT"},
}

// ClientHintMapping maps OS names to known client hint values.
// Mirrors PHP OperatingSystem::$clientHintMapping
var ClientHintMapping = map[string][]string{
	"GNU/Linux": {"Linux"},
	"Mac":       {"MacOS"},
}

// DesktopOsFamilies contains OS families that are known as desktop only.
// Mirrors PHP OperatingSystem::$desktopOsArray
var DesktopOsFamilies = []string{
	"AmigaOS", "IBM", "GNU/Linux", "Mac", "Unix", "Windows", "BeOS", "Chrome OS",
	"OpenVMS",
}

// FireOsVersionMapping maps Android versions to Fire OS versions.
// Mirrors PHP OperatingSystem::$fireOsVersionMapping
var FireOsVersionMapping = map[string]string{
	"14":    "14",
	"13":    "14",
	"12":    "14",
	"11":    "8",
	"10":    "8",
	"9":     "7",
	"7":     "6",
	"5":     "5",
	"4.4.3": "4.5.1",
	"4.4.2": "4",
	"4.2.2": "3",
	"4.0.3": "3",
	"4.0.2": "3",
	"4":     "2",
	"2":     "1",
}

// LineageOsVersionMapping maps Android versions to Lineage OS versions.
// Mirrors PHP OperatingSystem::$lineageOsVersionMapping
var LineageOsVersionMapping = map[string]string{
	"16":    "23",
	"15":    "22",
	"14":    "21",
	"13":    "20.0",
	"12.1":  "19.1",
	"12":    "19.0",
	"11":    "18.0",
	"10":    "17.0",
	"9":     "16.0",
	"8.1.0": "15.1",
	"8.0.0": "15.0",
	"7.1.2": "14.1",
	"7.1.1": "14.1",
	"7.0":   "14.0",
	"6.0.1": "13.0",
	"6.0":   "13.0",
	"5.1.1": "12.1",
	"5.0.2": "12.0",
	"5.0":   "12.0",
	"4.4.4": "11.0",
	"4.3":   "10.2",
	"4.2.2": "10.1",
	"4.0.4": "9.1.0",
}

// AndroidApps contains app IDs that indicate Android OS.
var AndroidApps = []string{
	"com.hisense.odinbrowser",
	"com.seraphic.openinet.pre",
	"com.appssppa.idesktoppcbrowser",
	"every.browser.inc",
}
